const pilotos = ['Vettel', 'Alonso', 'Raikkonen', 'Massa']
console.log('Pilotos da corrida ->', pilotos)
console.log()
console.log('pop()')
pilotos.pop()
console.log('Massa quebrou o carro!', pilotos)
console.log('push()')
pilotos.push('Verstappen')
console.log('Verstappen entrou na corrida!', pilotos)
console.log('shift()')
pilotos.shift()
console.log('Vettel saiu da corrida!', pilotos)
console.log('unshift()')
pilotos.unshift('Hamilton')
console.log('Hamilton entrou na primeira posição!', pilotos)
console.log('splice()')
pilotos.splice(2, 0, 'Bottas', 'Kubica')
console.log('Bottas e Kubica entraram antes de Raikkonen!', pilotos)
pilotos.splice(3, 1)
console.log('Kubica furou o pneu!', pilotos)
console.log('slice()')
let tresMelhores = pilotos.slice(0, 3)
console.log('Ganhadores do pódio!', tresMelhores)
let refrescados = pilotos.slice(3)
console.log('Pilotos que foram para a refrescagem ->', refrescados)